Contributing.md
dmayo3/mocksafe pull request #69
Opened 2024-10-19 08:48 UTC by Brijeshthummar02

issue #18

2024-10-20 04:35 UTC, Brijeshthummar02 commented
@dmayo3 any update?

2024-10-20 10:48 UTC, dmayo3 commented
> @dmayo3 any update?

Hi

Thanks for your contribution!

I haven't had any time to look at this properly yet. I'm busy this weekend, I will try to look at it this coming week.

2024-10-21 16:56 UTC, dmayo3 requested changes
Thanks for adding this @Brijeshthummar02 !

There is one minor issue with the reference to `requirements.txt` as this doesn't exist in this project - see the comments for more details. Otherwise it looks pretty good 👍 

I added a few other minor suggestions for improvement as well.

2024-10-21 16:56 UTC, dmayo3 commented on CONTRIBUTING.md
> +By participating in this project, you are expected to uphold the [Contributor Covenant Code of Conduct](CODE_OF_CONDUCT.md). Please ensure your behavior aligns with our pledge for a welcoming and inc
I don't know if this link works?

If you're sure it's okay then don't worry, but otherwise perhaps it might be best to use the full URL?

```suggestion
By participating in this project, you are expected to uphold the [Contributor Covenant Code of Conduct](https://github.com/dmayo3/mocksafe/blob/main/CODE_OF_CONDUCT.md). Please ensure your behavior aligns with our pledge for a welcoming and inclusive community.
```

2024-10-21 16:56 UTC, dmayo3 commented on CONTRIBUTING.md
> +By contributing to MockSafe, you agree that your contributions will be licensed under the MIT License. For more details, please see the [LICENSE] file.
```suggestion
By contributing to MockSafe, you agree that your contributions will be licensed under the MIT License. For more details, please see the [LICENSE](https://github.com/dmayo3/mocksafe/blob/main/LICENSE) file.
```

2024-10-21 16:56 UTC, dmayo3 commented on CONTRIBUTING.md
> +   pip install -r requirements.txt
This project uses `pyproject.toml` rather than `requirements.txt`.

I believe the correct command to use in this case would be: `pip install .` or `pip install -e .` for editable installs.

This step could be optional though if the developer chooses to use `tox` instead (see comment below).

2024-10-21 16:56 UTC, dmayo3 commented on CONTRIBUTING.md
> +
Maybe add an optional section about using `tox` to run tests, formatting, linting, build the docs, etc:

To run tests with tox first install with `pip install tox` then run:

```bash
tox
```

2024-10-22 14:43 UTC, Brijeshthummar02 commented
@dmayo3 by mistake added version update commit to this pr, i'll be deleting it don't worry about it, also working on comments you provided.

2024-10-22 15:16 UTC, Brijeshthummar02 commented
@dmayo3 looks good according to me, go through it once.

2024-10-22 16:48 UTC, dmayo3 approved these changes
Great, thanks 👍

2024-10-22 16:49 UTC, merged